/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Fiches;

import java.awt.geom.RoundRectangle2D;
import javax.swing.JLabel;
/**
 *
 * @author ivan5
 */
public class FCharger extends javax.swing.JDialog {

    /**
     * Creates new form FCharger
     */
    
    private String NomJoueurCharge;
    
    public FCharger(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),50,50));
        jErreur.setVisible(false);
        JInvalidePseudo.setVisible(false);
    }

    public String getNomJoueurCharge() {
        return NomJoueurCharge;
    }

    public JLabel getJInvalidePseudo() {
        return JInvalidePseudo;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bRetour = new javax.swing.JButton();
        bCharger1 = new javax.swing.JButton();
        JPseudo = new javax.swing.JTextField();
        jErreur = new javax.swing.JLabel();
        JInvalidePseudo = new javax.swing.JLabel();
        JFondCharger = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(320, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bRetour.setBackground(new java.awt.Color(255, 0, 255));
        bRetour.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bRetour.setForeground(new java.awt.Color(255, 255, 255));
        bRetour.setText("Retour");
        bRetour.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bRetour.setFocusable(false);
        bRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRetourActionPerformed(evt);
            }
        });
        getContentPane().add(bRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 40));

        bCharger1.setBackground(new java.awt.Color(102, 102, 255));
        bCharger1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bCharger1.setForeground(new java.awt.Color(255, 255, 255));
        bCharger1.setText("Charger");
        bCharger1.setActionCommand("Charger");
        bCharger1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bCharger1.setFocusable(false);
        bCharger1.setMaximumSize(new java.awt.Dimension(130, 25));
        bCharger1.setMinimumSize(new java.awt.Dimension(130, 25));
        bCharger1.setPreferredSize(new java.awt.Dimension(130, 25));
        bCharger1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCharger1ActionPerformed(evt);
            }
        });
        getContentPane().add(bCharger1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 110, 40));

        JPseudo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JPseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPseudoActionPerformed(evt);
            }
        });
        getContentPane().add(JPseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 140, 30));

        jErreur.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jErreur.setForeground(new java.awt.Color(204, 0, 0));
        jErreur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Attention2.png"))); // NOI18N
        jErreur.setText("️Veuillez entrer un pseudo !!");
        getContentPane().add(jErreur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 330, 50));

        JInvalidePseudo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        JInvalidePseudo.setForeground(new java.awt.Color(204, 0, 0));
        JInvalidePseudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Attention2.png"))); // NOI18N
        JInvalidePseudo.setText("Aucune sauvegarde à ce nom !!");
        getContentPane().add(JInvalidePseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 163, -1, -1));

        JFondCharger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fond_FCharger_.gif"))); // NOI18N
        getContentPane().add(JFondCharger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRetourActionPerformed
        // TODO add your handling code here:
        jErreur.setVisible(false);
        this.getParent().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bRetourActionPerformed

    private void bCharger1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCharger1ActionPerformed
        // TODO add your handling code here:
        NomJoueurCharge = JPseudo.getText();
        if (JPseudo.getText().equals("")){
            JInvalidePseudo.setVisible(false);
            jErreur.setVisible(true);
        }
        else{
            jErreur.setVisible(false);
            FJouer fJouer=((FAccueil)getParent()).getFichJouer();
            fJouer.Init();
        }
    }//GEN-LAST:event_bCharger1ActionPerformed

    private void JPseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPseudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCharger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCharger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCharger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCharger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FCharger dialog = new FCharger(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JFondCharger;
    private javax.swing.JLabel JInvalidePseudo;
    private javax.swing.JTextField JPseudo;
    private javax.swing.JButton bCharger1;
    private javax.swing.JButton bRetour;
    private javax.swing.JLabel jErreur;
    // End of variables declaration//GEN-END:variables

    
}
